In [48]:
import pandas as pd
import datetime
import numpy as np

In [49]:
borename = str(input())

1206

In [59]:
df = pd.read_excel(f'Z:2-UGIR\ONtrim\Нестеров С\Куюмбинское месторождение\\{borename}.xlsx')

In [60]:
df

,Насос,Мес,МЭР,ТР,Unnamed: 4,Парам/Дата,1,2,3,4,...,22,23,24,25,26,27,28,29,30,31
0,NaN,NaN,NaN,на авг 2023,Утв. на сен 2023,Состояние,раб.,ост.,ост.,ост.,...,ост.,ост.,ост.,ост.,ост.,ост.,ост.,ост.,ост.,ост.
1,"30.2ЭЦНДИ5А-125М-2050, глуб 2380 м, АФКЭ-65х21",август 2023,63.00,68,NaN,"Qж, м3/сут",1633,68,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,"Qж БМА, м3/сут",31,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,"Qж ПЗУ СП, м3/сут",402,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,74.45,75,NaN,"Обв, %",NaN,75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1315,NaN,NaN,NaN,NaN,NaN,Обр.,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1316,NaN,NaN,NaN,NaN,NaN,Прим,NaN,NaN,NaN,NaN,...,Продувка 40мин на факел на шт.14мм (профилакт...,КАСКАД фреза 51мм проход 1500м 0-600м гидратн...,NaN,КАСКАД фреза 51мм проход 1500м По заявке ЦДНГ...,NaN,КАСКАД фреза 51мм проход 1500м 400-650м незн...,NaN,Перевод работы скважин в НСК 114мм,NaN,NaN
1317,NaN,NaN,NaN,NaN,NaN,Ситуация,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1318,NaN,NaN,NaN,NaN,NaN,ОМ,БО,БО,БО,БО,...,13,БО,БО,БО,БО,НФ,БО,БО,БО,БО
1319,NaN,NaN,NaN,NaN,NaN,З. ДМ,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
df = df[df['Парам/Дата'].isin(['Состояние','Qж, м3/сут', 'Обв, %', 'Qн, т/сут', 'Qгаз, м3/сут', 'ГФ, м3/т', 'Рприем, атм'])]
df = df.iloc[:, 5:]
df = df.rename(columns={'Парам/Дата':'Дата'})
df = df.assign(idx=df.groupby('Дата').cumcount()).set_index('idx')

In [62]:
df

,Дата,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
idx,,,,,,,,,,,,,,,,,,,,,
0,Состояние,раб.,ост.,ост.,ост.,ост.,ост.,ост.,ост.,ост.,...,ост.,ост.,ост.,ост.,ост.,ост.,ост.,ост.,ост.,ост.
0,"Qж, м3/сут",1633,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"Обв, %",NaN,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"Qн, т/сут",334.765,13.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,"Qгаз, м3/сут",NaN,1711.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,"Обв, %",NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
43,"Qн, т/сут",105.272,105.272,105.272,105.272,115.718,105.272,115.718,115.718,115.718,...,115.718,110.736,110.897,110.897,110.897,110.897,110.897,110.897,110.897,112.028
43,"Qгаз, м3/сут",87375.43,87375.43,87375.43,87375.43,68852.45,62636.6,68852.45,68852.45,68852.45,...,68852.45,65887.98,65983.6,65983.6,65983.6,65983.6,65983.6,65983.6,65983.6,66656.9
43,"ГФ, м3/т",159,NaN,NaN,NaN,595,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,"Рприем, атм",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
res = pd.concat([df.loc[i].set_index('Дата').dropna(how='all', axis='columns') for i in list(range(43, -1, -1))], axis=1)
res = res.T
res.index = pd.date_range(start='01/01/2020', end='08/31/2023').date.tolist()
res.columns.name = None
res.index.name = 'Дата'

In [64]:
res

,Состояние,"Qж, м3/сут","Обв, %","Qн, т/сут","Qгаз, м3/сут","ГФ, м3/т","Рприем, атм"
Дата,,,,,,,
2020-01-01,раб.,131,NaN,105.272,87375.43,159,NaN
2020-01-02,раб.,131,NaN,105.272,87375.43,NaN,NaN
2020-01-03,раб.,131,NaN,105.272,87375.43,NaN,NaN
2020-01-04,раб.,131,NaN,105.272,87375.43,NaN,NaN
2020-01-05,раб.,144,NaN,115.718,68852.45,595,NaN
...,...,...,...,...,...,...,...
2023-08-27,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-28,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-29,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-30,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-31,ост.,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
res[res['Состояние'] == 'ост.']

,Состояние,"Qж, м3/сут","Обв, %","Qн, т/сут","Qгаз, м3/сут","ГФ, м3/т","Рприем, атм"
Дата,,,,,,,
2020-04-05,ост.,123,NaN,92.791,35724.61,NaN,NaN
2020-04-06,ост.,123,NaN,92.791,35724.61,NaN,NaN
2020-04-07,ост.,123,NaN,92.791,35724.61,NaN,NaN
2020-04-11,ост.,93,8,70.159,27011.29,NaN,NaN
2020-04-12,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2020-04-13,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2020-04-14,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2020-04-15,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2020-04-16,ост.,84,1,68.191,26253.61,NaN,155
2020-04-17,ост.,58,1,47.084,18127.49,NaN,151
2020-04-18,ост.,93,0.1,76.184,29330.73,NaN,142
2020-04-19,ост.,93,9.3,69.168,26629.6,NaN,144
2021-04-09,ост.,NaN,NaN,NaN,NaN,NaN,133.5
2021-06-27,ост.,95,60,31.16,3917,125.706,98
2023-04-18,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-04-19,ост.,NaN,NaN,NaN,NaN,NaN,124
2023-04-20,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-04-21,ост.,NaN,NaN,NaN,NaN,NaN,125.7
2023-04-22,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-04-23,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-04-24,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-04-25,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-04-26,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-04-27,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-04-28,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-04-29,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-04-30,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-05-01,ост.,NaN,NaN,NaN,NaN,NaN,86.5
2023-05-02,ост.,NaN,NaN,NaN,NaN,NaN,127
2023-05-03,ост.,NaN,NaN,NaN,NaN,NaN,127
2023-05-04,ост.,NaN,NaN,NaN,NaN,NaN,127
2023-05-05,ост.,NaN,NaN,NaN,NaN,NaN,127
2023-05-06,ост.,NaN,NaN,NaN,NaN,NaN,127
2023-05-07,ост.,NaN,NaN,NaN,NaN,NaN,127
2023-05-08,ост.,NaN,NaN,NaN,NaN,NaN,127
2023-05-09,ост.,NaN,NaN,NaN,NaN,NaN,127
2023-05-10,ост.,NaN,NaN,NaN,NaN,NaN,127.6
2023-05-11,ост.,53,80,8.692,NaN,207.897,100.1
2023-08-02,ост.,68,75,13.94,1711.99,122.811,75.5
2023-08-03,ост.,NaN,NaN,NaN,NaN,NaN,121.4
2023-08-04,ост.,NaN,NaN,NaN,NaN,NaN,122.8
2023-08-05,ост.,NaN,NaN,NaN,NaN,NaN,122.8
2023-08-06,ост.,NaN,NaN,NaN,NaN,NaN,122.2
2023-08-07,ост.,NaN,NaN,NaN,NaN,NaN,123
2023-08-08,ост.,NaN,NaN,NaN,NaN,NaN,123
2023-08-09,ост.,NaN,NaN,NaN,NaN,NaN,123.6
2023-08-10,ост.,NaN,NaN,NaN,NaN,NaN,123
2023-08-20,ост.,68,75,13.94,1711.99,122.811,80.2
2023-08-21,ост.,NaN,NaN,NaN,NaN,NaN,81.2
2023-08-22,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-23,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-24,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-25,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-26,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-27,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-28,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-29,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-30,ост.,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-31,ост.,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
res = res.dropna(subset='Рприем, атм')

In [57]:
res

,Состояние,"Qж, м3/сут","Обв, %","Qн, т/сут","Qгаз, м3/сут","ГФ, м3/т","Рприем, атм"
Дата,,,,,,,
2020-04-16,ост.,84,1,68.191,26253.61,NaN,155
2020-04-17,ост.,58,1,47.084,18127.49,NaN,151
2020-04-18,ост.,93,0.1,76.184,29330.73,NaN,142
2020-04-19,ост.,93,9.3,69.168,26629.6,NaN,144
2020-04-20,раб.,136,3,108.174,41647.14,NaN,140
...,...,...,...,...,...,...,...
2023-08-17,раб.,NaN,NaN,NaN,NaN,NaN,81.2
2023-08-18,раб.,NaN,NaN,NaN,NaN,NaN,83.4
2023-08-19,раб.,NaN,NaN,NaN,NaN,NaN,81.8
2023-08-20,ост.,68,75,13.94,1711.99,122.811,80.2
2023-08-21,ост.,NaN,NaN,NaN,NaN,NaN,81.2

In [58]:
with pd.ExcelWriter('Z:2-UGIR\ONtrim\Нестеров С\Куюмбинское месторождение\Form.xlsx', mode="a", engine="openpyxl",if_sheet_exists="replace") as writer:
    res.to_excel(writer, sheet_name=borename)